export const FIR_DATA: Record<string, string> = {
    "ACCRA": "DGAC",
    "ADDIS ABEBA": "HAAA",
    "AKTOBE": "UATT",
    "ALASKA": "PAZA",
    "ALBUQUERQUE": "KZAB",
    "ALGER": "DAAA",
    "ALMATY": "UAAA",
    "AMAZONICA": "SBAZ",
    "AMMAN": "OJAC",
    "AMSTERDAM": "EHAA",
    "ANKARA": "LTAA",
    "ANTANANARIVO": "FMMM",
    "ANTOFAGASTA": "SCFZ",
    "ARKHANGELSK": "ULAA",
    "ASHGABAT": "UTAA",
    "ASMARA": "HHAA",
    "ASUNCION": "SGFA",
    "ATHINAI": "LGGG",
    "ATLANTA": "KZTL",
    "ATLANTICO": "SBAO",
    "AUCKLAND OCEANIC": "NZZO",
    "BAGHDAD": "ORBB",
    "BAHRAIN": "OBBB",
    "BAKU": "UBBA",
    "BANGKOK": "VTBB",
    "BARCELONA": "LECB",
    "BARRANQUILLA": "SKEC",
    "BEIJING": "ZBPE",
    "BEIRA": "FQBE",
    "BEIRUT": "OLBB",
    "BEOGRAD": "LYBA",
    "BISHKEK": "UCFM",
    "BODO OCEANIC": "ENOB",
    "BOGOTA": "SKED",
    "BORDEAUX": "LFBB",
    "BOSTON": "KZBW",
    "BRASILIA": "SBBS",
    "BRATISLAVA": "LZBB",
    "BRAZZAVILLE": "FCCC",
    "BREMEN": "EDWW",
    "BREST": "LFRR",
    "BRINDISI": "LIBB",
    "BRISBANE": "YBBB",
    "BRUSSELS": "EBUR",
    "BUCAREST": "LRBB",
    "BUDAPEST": "LHCC",
    "BUJUMBURA": "HBBA",
    "CAIRO": "HECC",
    "CANARIAS": "GCCC",
    "CAPE TOWN": "FACA",
    "CASABLANCA": "GMMM",
    "CAYENNE": "SOOO",
    "CENTRAL AMERICA": "MHCC",
    "CHENNAI": "VOMF",
    "CHICAGO": "KZAU",
    "CHISINAU": "LUUU",
    "CLEVELAND": "KZOB",
    "COLOMBO": "VCCF",
    "COMODORO RIVADAVIA": "SAVF",
    "COPENHAGEN": "EKDK",
    "CORDOBA": "SACF",
    "CURACAO": "TNCF",
    "CURITIBA": "SBCW",
    "DAKAR": "GOOO",
    "DAMASCUS": "OSTT",
    "DAR-ES-SALAAM": "HTDC",
    "DASHOGUZ": "UTAT",
    "DELHI": "VIDF",
    "DENVER": "KZDV",
    "DHAKA": "VGFR",
    "DNIPRO": "UKDV",
    "DOHA": "OTDF",
    "DUSHANBE": "UTDD",
    "EDMONTON": "CZEG",
    "EMIRATES": "OMAE",
    "ENTEBBE": "HUEC",
    "EZEIZA": "SAEF",
    "FORT WORTH": "KZFW",
    "FRANCE": "LFFF",
    "FUKUOKA": "RJJJ",
    "GABORONE": "FBGR",
    "GANDER": "CZQX",
    "GEORGETOWN": "SYGC",
    "GUANGZHOU": "ZGZU",
    "GUAYAQUIL": "SEFG",
    "HABANA": "MUFH",
    "HANNOVER": "EDVV",
    "HANOI": "VVVV",
    "HARARE": "FVHF",
    "HELSINKI": "EFIN",
    "HO CHI MINH": "VVTS",
    "HONG KONG": "VHHK",
    "HONIARA": "AGGG",
    "HOUSTON": "KZHU",
    "INCHEON": "RKRR",
    "INDIANAPOLIS": "KZID",
    "IRKUTSK": "UIII",
    "ISLA DE PASCUA": "SCIZ",
    "ISTANBUL": "LTBB",
    "JACKSONVILLE": "KZJX",
    "JAKARTA": "WIIF",
    "JEDDAH": "OEJD",
    "JOHANNESBURG": "FAJA",
    "JOHANNESBURG OCEANIC": "FAJO",
    "KABUL": "OAKX",
    "KALININGRAD": "UMKK",
    "KANO": "DNKK",
    "KANSAS CITY": "KZKC",
    "KARACHI": "OPKR",
    "KATHMANDU": "VNSM",
    "KHABAROVSK": "UHHH",
    "KHARTOUM": "HSSS",
    "KIEV": "UKBV",
    "KIGALI": "HRYR",
    "KINGSTON": "MKJK",
    "KINSHASA": "FZZA",
    "KOLKATA": "VECF",
    "KOTA KINABALU": "WBFC",
    "KOTLAS": "ULKK",
    "KRASNOYARSK": "UNKL",
    "KUALA LUMPUR": "WMFC",
    "KUNMING": "ZPKM",
    "KUWAIT": "OKAC",
    "LA PAZ": "SLLF",
    "LAHORE": "OPLR",
    "LANGEN": "EDGG",
    "LANZHOU": "ZLHW",
    "LILONGWE": "FWLL",
    "LIMA": "SPIM",
    "LISBOA": "LPPC",
    "LJUBLJANA": "LJLA",
    "LONDON": "EGTT",
    "LOS ANGELES": "KZLA",
    "LUANDA": "FNAN",
    "LUSAKA": "FLFI",
    "LVOV": "UKLV",
    "MADRID": "LECM",
    "MAGADAN": "UHMM",
    "MAIQUETIA": "SVZM",
    "MALE": "VRMF",
    "MALTA": "LMMM",
    "MANILA": "RPHI",
    "MARSEILLE": "LFMM",
    "MAURITIUS": "FIMM",
    "MELBOURNE": "YMMM",
    "MEMPHIS": "KZME",
    "MENDOZA": "SAMF",
    "MEXICO": "MMFR",
    "MIAMI": "KZMA",
    "MILANO": "LIMM",
    "MINNEAPOLIS": "KZMP",
    "MINSK": "UMMV",
    "MOGADISHU": "HCSM",
    "MONCTON": "CZQM",
    "MONTEVIDEO": "SUEO",
    "MONTREAL": "CZUL",
    "MOSCOW": "UUWV",
    "MUMBAI": "VABF",
    "MUNCHEN": "EDMM",
    "MURMANSK": "ULMM",
    "MUSCAT": "OOMM",
    "N'DJAMENA": "FTTT",
    "NADI": "NFFF",
    "NAIROBI": "HKNA",
    "NAURU": "ANAU",
    "NEW YORK": "KZNY",
    "NEW YORK OCEANIC": "KZWY",
    "NEW ZEALAND": "NZZC",
    "NIAMEY": "DRRR",
    "NICOSIA": "LCCC",
    "NOVOSIBIRSK": "UNNT",
    "NUR-SULTAN": "UACN",
    "NUUK": "BGGL",
    "OAKLAND": "KZOA",
    "OAKLAND OCEANIC": "KZAK",
    "OCEANICA MAZATLAN": "MMFO",
    "ODESSA": "UKOV",
    "OSH": "UCFO",
    "PANAMA": "MPZL",
    "PARAMARIBO": "SMPM",
    "PARIS": "LFFF",
    "PETROPAVLOVSK-KAMCHATSKY": "UHPP",
    "PHNOM PENH": "VDPF",
    "PIARCO": "TTZP",
    "POLARIS": "ENOR",
    "PORT MORESBY": "AYPM",
    "PORT-AU-PRINCE": "MTEG",
    "PRAHA": "LKAA",
    "PUERTO MONTT": "SCTZ",
    "PUNTA ARENAS": "SCCZ",
    "PYONGYANG": "ZKKP",
    "RECIFE": "SBRE",
    "REIMS": "LFEE",
    "RESISTENCIA": "SARR",
    "REYKJAVIK": "BIRD",
    "RHEIN": "EDUU",
    "RIGA": "EVRR",
    "ROBERTS": "GLRB",
    "ROMA": "LIRR",
    "ROSTOV-NA-DONU": "URRV",
    "SAL OCEANIC": "GVSC",
    "SALT LAKE CITY": "KZLC",
    "SAMARA": "UWWW",
    "SAMARKAND": "UTSD",
    "SAN JUAN OCEANIC": "TJZS",
    "SANAA": "OYSC",
    "SANKT-PETERBURG": "ULLL",
    "SANTA MARIA": "LPPO",
    "SANTIAGO": "SCEZ",
    "SANTO DOMINGO": "MDCS",
    "SANYA": "ZJSA",
    "SARAJEVO": "LQSB",
    "SCOTTISH": "EGPX",
    "SEATTLE": "KZSE",
    "SEYCHELLES": "FSSS",
    "SHANGHAI": "ZSHA",
    "SHANNON": "EISN",
    "SHANWICK": "EGGX",
    "SHENYANG": "ZYSH",
    "SHYMKENT": "UAII",
    "SIMFEROPOL": "UKFV",
    "SINGAPORE": "WSJC",
    "SKOPJE": "LWSS",
    "SOFIA": "LBSR",
    "SWEDEN": "ESAA",
    "SWITZERLAND": "LSAS",
    "SYKTYVKAR": "UUYY",
    "TAHITI OCEANIC": "NTTT",
    "TAIPEI": "RCAA",
    "TALLINN": "EETT",
    "TASHKENT": "UTTR",
    "TEHRAN": "OIIX",
    "TEL-AVIV": "LLLL",
    "TIBILISI": "UGGG",
    "TIRANA": "LAAA",
    "TORONTO": "CZYZ",
    "TRIPOLI": "HLLL",
    "TUNIS": "DTTC",
    "TURKMENABAT": "UTAV",
    "TURKMENBASHI": "UTAK",
    "TYUMEN": "USTV",
    "U-JUNG PANDANG": "WAAF",
    "ULAANBAATAR": "ZMUB",
    "URUMQI": "ZWUQ",
    "VANCOUVER": "CZVR",
    "VIENTIANE": "VLVT",
    "VILNIUS": "EYVL",
    "VOLOGDA": "ULWW",
    "WARSZAWA": "EPWW",
    "WASHINGTON": "KZDC",
    "WIEN": "LOVV",
    "WINDHOEK": "FYWF",
    "WINNIPEG": "CZWG",
    "WUHAN": "ZHWH",
    "YAKUTSK": "UEEE",
    "YANGON": "VYYF",
    "YEKATERINBURG": "USSV",
    "YEREVAN": "UDDD",
    "ZAGREB": "LDZO"
};